### PR TITLE
Change project license [v2]

### PR DESCRIPTION
**Pull request by bdilly**

### CODE REVIEW

**Comment by bdilly** [comment]
fix issue with v1 #69

**Comment by cabelitos** [comment]
@bdilly There are some files that does not have licenses in it:
soletta_module/samples/light.fbp
soletta_module/samples/sml_garden/flower_power.py
sml/common/include/config.in

The json configuration files (Do they need license?)

**Comment by bdilly** [comment]
Most of json files don't need it (soletta's description json files have fields for license)

These other files you just spotted require license headers. I'll add it. Thank you

**Comment by bdilly** [comment]
@cabelitos these files you mentioned don't exist in our repository

**Comment by bdilly** [comment]
merged, thanks

**Pull request closed without merging**
